package project

import (
	"fmt"

	"github.com/paolo/flare-edge-cli/internal/domain/config"
)

const defaultGitignore = ".wrangler/\ndist/\nnode_modules/\n"

func scaffoldFiles(project config.Project) map[string]string {
	return map[string]string{
		"README.md":                          readmeTemplate(project),
		".gitignore":                         defaultGitignore,
		"go.mod":                             fmt.Sprintf("module %s\n\ngo 1.26.0\n", project.ModulePath),
		"cmd/worker/main.go":                 workerMainTemplate(project),
		"internal/generated/worker_shim.mjs": workerShimTemplate(project.WasmFile),
	}
}

func readmeTemplate(project config.Project) string {
	return fmt.Sprintf("# %s\n\nGenerated by flare-edge-cli.\n", project.ProjectName)
}

func workerMainTemplate(project config.Project) string {
	message := "hello from flare-edge-cli"
	switch project.Template {
	case "edge-json":
		message = "{\"ok\":true}"
	case "scheduled":
		message = "scheduled handler ready"
	case "kv-api":
		message = "kv binding ready"
	case "d1-api":
		message = "d1 binding ready"
	case "r2-api":
		message = "r2 binding ready"
	}

	return fmt.Sprintf(`package main

import "syscall/js"

func main() {
	js.Global().Set("handleRequest", js.FuncOf(func(this js.Value, args []js.Value) any {
		return %q
	}))
	js.Global().Set("handleScheduled", js.FuncOf(func(this js.Value, args []js.Value) any {
		return nil
	}))
	select {}
}
`, message)
}

func workerShimTemplate(wasmFile string) string {
	return fmt.Sprintf(`import "./wasm_exec.js";

const go = new Go();
let ready;

async function boot() {
  if (!ready) {
    ready = (async () => {
      const response = await fetch(new URL("./%s", import.meta.url));
      const result = await WebAssembly.instantiateStreaming(response, go.importObject);
      go.run(result.instance);
      for (let i = 0; i < 100; i += 1) {
        if (typeof globalThis.handleRequest === "function") {
          return;
        }
        await Promise.resolve();
      }
      throw new Error("Go handler did not register globalThis.handleRequest");
    })();
  }
  await ready;
}

function toResponse(result) {
  if (result instanceof Response) {
    return result;
  }
  if (typeof result === "string") {
    return new Response(result);
  }
  if (result && typeof result === "object" && "body" in result) {
    return new Response(result.body, {
      status: result.status ?? 200,
      headers: result.headers ?? {},
    });
  }
  return new Response("");
}

export default {
  async fetch(request, env, ctx) {
    await boot();
    return toResponse(await globalThis.handleRequest(request, env, ctx));
  },
  async scheduled(controller, env, ctx) {
    await boot();
    if (typeof globalThis.handleScheduled === "function") {
      await globalThis.handleScheduled(controller, env, ctx);
    }
  },
};
`, wasmFile)
}

func WorkerShimTemplate(wasmFile string) string {
	return workerShimTemplate(wasmFile)
}
