package project

import (
	"fmt"

	"github.com/paolo/flare-edge-cli/internal/domain/config"
)

const defaultGitignore = ".wrangler/\ndist/\nnode_modules/\n"

func scaffoldFiles(project config.Project) map[string]string {
	return map[string]string{
		"README.md":                          readmeTemplate(project),
		".gitignore":                         defaultGitignore,
		"go.mod":                             fmt.Sprintf("module %s\n\ngo 1.26.0\n", project.ModulePath),
		"cmd/worker/main.go":                 workerMainTemplate(project),
		"internal/generated/worker_shim.mjs": workerShimTemplate(project.WasmFile),
	}
}

func readmeTemplate(project config.Project) string {
	return fmt.Sprintf("# %s\n\nGenerated by flare-edge-cli.\n", project.ProjectName)
}

func workerMainTemplate(project config.Project) string {
	if project.Template == "ai-text" {
		return aiWorkerMainTemplate()
	}

	message := "hello from flare-edge-cli"
	switch project.Template {
	case "edge-json":
		message = "{\"ok\":true}"
	case "scheduled":
		message = "scheduled handler ready"
	case "kv-api":
		message = "kv binding ready"
	case "d1-api":
		message = "d1 binding ready"
	case "r2-api":
		message = "r2 binding ready"
	}

	return fmt.Sprintf(`package main

import "syscall/js"

func main() {
	js.Global().Set("handleRequest", js.FuncOf(func(this js.Value, args []js.Value) any {
		return %q
	}))
	js.Global().Set("handleScheduled", js.FuncOf(func(this js.Value, args []js.Value) any {
		return nil
	}))
	select {}
}
`, message)
}

func aiWorkerMainTemplate() string {
	return `package main

import "syscall/js"

const defaultAIModel = "@cf/meta/llama-3.1-8b-instruct"

func main() {
	js.Global().Set("handleRequest", js.FuncOf(handleRequest))
	js.Global().Set("handleScheduled", js.FuncOf(func(this js.Value, args []js.Value) any {
		return nil
	}))
	select {}
}

func handleRequest(this js.Value, args []js.Value) any {
	if len(args) < 2 {
		return textResponse(500, "missing request or env")
	}

	request := args[0]
	env := args[1]
	ai := env.Get("AI")
	if ai.IsUndefined() || ai.IsNull() {
		return textResponse(500, "Workers AI binding \"AI\" is not configured")
	}

	url := js.Global().Get("URL").New(request.Get("url"))
	prompt := searchParam(url, "prompt")
	if prompt == "" {
		prompt = "Say hello from a Go-based Cloudflare AI Worker."
	}
	model := searchParam(url, "model")
	if model == "" {
		model = defaultAIModel
	}

	input := js.Global().Get("Object").New()
	input.Set("prompt", prompt)

	return promise(func(resolve, reject js.Value) {
		var onResolve js.Func
		var onReject js.Func

		onResolve = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()

			payload := "null"
			if len(args) > 0 {
				payload = stringify(args[0])
			}
			resolve.Invoke(jsonResponse(payload))
			return nil
		})

		onReject = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()

			message := "Workers AI request failed"
			status := 502
			if len(args) > 0 {
				message = errorPayload(args[0])
				if code := errorStatus(args[0]); code > 0 {
					status = code
				}
			}
			resolve.Invoke(jsonTextResponse(status, message))
			return nil
		})

		ai.Call("run", model, input).Call("then", onResolve).Call("catch", onReject)
	})
}

func promise(fn func(resolve js.Value, reject js.Value)) js.Value {
	executor := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) >= 2 {
			fn(args[0], args[1])
		}
		return nil
	})
	defer executor.Release()

	return js.Global().Get("Promise").New(executor)
}

func stringify(value js.Value) string {
	output := js.Global().Get("JSON").Call("stringify", value)
	if output.IsUndefined() || output.IsNull() {
		return "null"
	}
	return output.String()
}

func errorPayload(value js.Value) string {
	payload := js.Global().Get("Object").New()
	payload.Set("name", value.Get("name"))
	payload.Set("message", value.Get("message"))
	payload.Set("code", firstDefined(value, "code", "status"))
	payload.Set("internalCode", firstDefined(value, "internalCode", "internal_code"))

	cause := value.Get("cause")
	if !cause.IsUndefined() && !cause.IsNull() {
		causePayload := js.Global().Get("Object").New()
		causePayload.Set("name", cause.Get("name"))
		causePayload.Set("message", cause.Get("message"))
		causePayload.Set("code", firstDefined(cause, "code", "status"))
		causePayload.Set("internalCode", firstDefined(cause, "internalCode", "internal_code"))
		payload.Set("cause", causePayload)
	}

	text := stringify(payload)
	if text == "{}" || text == "null" {
		return "{\"message\":\"Workers AI request failed\"}"
	}
	return text
}

func errorStatus(value js.Value) int {
	for _, key := range []string{"status", "statusCode", "code"} {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() && field.Type() == js.TypeNumber {
			return field.Int()
		}
	}
	return 0
}

func firstDefined(value js.Value, keys ...string) js.Value {
	for _, key := range keys {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() {
			return field
		}
	}
	return js.Null()
}

func searchParam(url js.Value, key string) string {
	value := url.Get("searchParams").Call("get", key)
	if value.IsUndefined() || value.IsNull() {
		return ""
	}
	return value.String()
}

func jsonResponse(body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "application/json")
	options := js.Global().Get("Object").New()
	options.Set("status", 200)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}

func jsonTextResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "application/json")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}

func textResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "text/plain; charset=utf-8")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}
`
}

func workerShimTemplate(wasmFile string) string {
	return fmt.Sprintf(`import "./wasm_exec.js";
import wasmModule from "./%s";

const go = new Go();
let ready;

function wasmInstance(result) {
  if (result instanceof WebAssembly.Instance) {
    return result;
  }
  if (result && result.instance instanceof WebAssembly.Instance) {
    return result.instance;
  }
  throw new TypeError("unsupported WebAssembly instantiate result");
}

async function boot() {
  if (!ready) {
    ready = (async () => {
      const result = await WebAssembly.instantiate(wasmModule, go.importObject);
      const runtime = go.run(wasmInstance(result));
      const waitForHandler = (async () => {
        for (let i = 0; i < 200; i += 1) {
          if (typeof globalThis.handleRequest === "function") {
            return;
          }
          await new Promise((resolve) => setTimeout(resolve, 5));
        }
        throw new Error("Go handler did not register globalThis.handleRequest");
      })();
      await Promise.race([
        waitForHandler,
        runtime.then(() => {
          throw new Error("Go runtime exited before handler registration");
        }),
      ]);
    })();
  }
  await ready;
}

function toResponse(result) {
  if (result instanceof Response) {
    return result;
  }
  if (typeof result === "string") {
    return new Response(result);
  }
  if (result && typeof result === "object" && "body" in result) {
    return new Response(result.body, {
      status: result.status ?? 200,
      headers: result.headers ?? {},
    });
  }
  return new Response("");
}

export default {
  async fetch(request, env, ctx) {
    await boot();
    return toResponse(await globalThis.handleRequest(request, env, ctx));
  },
  async scheduled(controller, env, ctx) {
    await boot();
    if (typeof globalThis.handleScheduled === "function") {
      await globalThis.handleScheduled(controller, env, ctx);
    }
  },
};
`, wasmFile)
}

func WorkerShimTemplate(wasmFile string) string {
	return workerShimTemplate(wasmFile)
}
