package project

import (
	"fmt"

	"github.com/paolo/flare-edge-cli/internal/domain/config"
)

const defaultGitignore = ".wrangler/\ndist/\nnode_modules/\n"

func scaffoldFiles(project config.Project) map[string]string {
	return map[string]string{
		"README.md":                          readmeTemplate(project),
		".gitignore":                         defaultGitignore,
		"go.mod":                             fmt.Sprintf("module %s\n\ngo 1.26.0\n", project.ModulePath),
		"cmd/worker/main.go":                 workerMainTemplate(project),
		"internal/generated/worker_shim.mjs": workerShimTemplate(project.WasmFile),
	}
}

func readmeTemplate(project config.Project) string {
	return fmt.Sprintf("# %s\n\nGenerated by flare-edge-cli.\n", project.ProjectName)
}

func workerMainTemplate(project config.Project) string {
	message := "hello from flare-edge-cli"
	switch project.Template {
	case "ai-text", "ai-chat":
		return aiChatWorkerMainTemplate()
	case "ai-vision":
		return aiVisionWorkerMainTemplate()
	case "ai-stt":
		return aiSTTWorkerMainTemplate()
	case "ai-tts":
		return aiTTSWorkerMainTemplate()
	case "ai-image":
		return aiImageWorkerMainTemplate()
	case "ai-embeddings":
		return aiEmbeddingsWorkerMainTemplate()
	case "edge-json":
		message = "{\"ok\":true}"
	case "scheduled":
		message = "scheduled handler ready"
	case "kv-api":
		message = "kv binding ready"
	case "d1-api":
		message = "d1 binding ready"
	case "r2-api":
		message = "r2 binding ready"
	}

	return fmt.Sprintf(`package main

import "syscall/js"

func main() {
	js.Global().Set("handleRequest", js.FuncOf(func(this js.Value, args []js.Value) any {
		return %q
	}))
	js.Global().Set("handleScheduled", js.FuncOf(func(this js.Value, args []js.Value) any {
		return nil
	}))
	select {}
}
	`, message)
}

func aiChatWorkerMainTemplate() string {
	return `package main

import "syscall/js"

const defaultAIModel = "@cf/moonshotai/kimi-k2.5"

func main() {
	js.Global().Set("handleRequest", js.FuncOf(handleRequest))
	js.Global().Set("handleScheduled", js.FuncOf(func(this js.Value, args []js.Value) any {
		return nil
	}))
	select {}
}

func handleRequest(this js.Value, args []js.Value) any {
	if len(args) < 2 {
		return textResponse(500, "missing request or env")
	}

	request := args[0]
	env := args[1]
	ai := env.Get("AI")
	if ai.IsUndefined() || ai.IsNull() {
		return textResponse(500, "Workers AI binding \"AI\" is not configured")
	}

	url := js.Global().Get("URL").New(request.Get("url"))
	prompt := searchParam(url, "prompt")
	if prompt == "" {
		prompt = "Say hello from a Go-based Cloudflare AI Worker."
	}
	model := searchParam(url, "model")
	if model == "" {
		model = defaultAIModel
	}

	input := js.Global().Get("Object").New()
	messages := js.Global().Get("Array").New()
	user := js.Global().Get("Object").New()
	user.Set("role", "user")
	user.Set("content", prompt)
	messages.Call("push", user)
	input.Set("messages", messages)

	return promise(func(resolve, reject js.Value) {
		var onResolve js.Func
		var onReject js.Func

		onResolve = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()

			payload := "null"
			if len(args) > 0 {
				payload = stringify(args[0])
			}
			resolve.Invoke(jsonResponse(payload))
			return nil
		})

		onReject = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()

			message := "Workers AI request failed"
			status := 502
			if len(args) > 0 {
				message = errorPayload(args[0])
				if code := errorStatus(args[0]); code > 0 {
					status = code
				}
			}
			resolve.Invoke(jsonTextResponse(status, message))
			return nil
		})

		ai.Call("run", model, input).Call("then", onResolve).Call("catch", onReject)
	})
}

func promise(fn func(resolve js.Value, reject js.Value)) js.Value {
	executor := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) >= 2 {
			fn(args[0], args[1])
		}
		return nil
	})
	defer executor.Release()

	return js.Global().Get("Promise").New(executor)
}

func stringify(value js.Value) string {
	output := js.Global().Get("JSON").Call("stringify", value)
	if output.IsUndefined() || output.IsNull() {
		return "null"
	}
	return output.String()
}

func errorPayload(value js.Value) string {
	payload := js.Global().Get("Object").New()
	payload.Set("name", value.Get("name"))
	payload.Set("message", value.Get("message"))
	payload.Set("code", firstDefined(value, "code", "status"))
	payload.Set("internalCode", firstDefined(value, "internalCode", "internal_code"))

	cause := value.Get("cause")
	if !cause.IsUndefined() && !cause.IsNull() {
		causePayload := js.Global().Get("Object").New()
		causePayload.Set("name", cause.Get("name"))
		causePayload.Set("message", cause.Get("message"))
		causePayload.Set("code", firstDefined(cause, "code", "status"))
		causePayload.Set("internalCode", firstDefined(cause, "internalCode", "internal_code"))
		payload.Set("cause", causePayload)
	}

	text := stringify(payload)
	if text == "{}" || text == "null" {
		return "{\"message\":\"Workers AI request failed\"}"
	}
	return text
}

func errorStatus(value js.Value) int {
	for _, key := range []string{"status", "statusCode", "code"} {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() && field.Type() == js.TypeNumber {
			return field.Int()
		}
	}
	return 0
}

func firstDefined(value js.Value, keys ...string) js.Value {
	for _, key := range keys {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() {
			return field
		}
	}
	return js.Null()
}

func searchParam(url js.Value, key string) string {
	value := url.Get("searchParams").Call("get", key)
	if value.IsUndefined() || value.IsNull() {
		return ""
	}
	return value.String()
}

func jsonResponse(body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "application/json")
	options := js.Global().Get("Object").New()
	options.Set("status", 200)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}

func jsonTextResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "application/json")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}

func textResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "text/plain; charset=utf-8")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}
`
}

func aiVisionWorkerMainTemplate() string {
	return `package main

import "syscall/js"

const defaultAIModel = "@cf/moonshotai/kimi-k2.5"

func main() {
	js.Global().Set("handleRequest", js.FuncOf(handleRequest))
	js.Global().Set("handleScheduled", js.FuncOf(func(this js.Value, args []js.Value) any {
		return nil
	}))
	select {}
}

func handleRequest(this js.Value, args []js.Value) any {
	if len(args) < 2 {
		return textResponse(500, "missing request or env")
	}

	request := args[0]
	env := args[1]
	ai := env.Get("AI")
	if ai.IsUndefined() || ai.IsNull() {
		return textResponse(500, "Workers AI binding \"AI\" is not configured")
	}

	url := js.Global().Get("URL").New(request.Get("url"))
	prompt := searchParam(url, "prompt")
	if prompt == "" {
		prompt = "Describe this image."
	}
	imageURL := searchParam(url, "image_url")
	if imageURL == "" {
		return jsonTextResponse(400, "{\"message\":\"image_url query parameter is required\"}")
	}
	model := searchParam(url, "model")
	if model == "" {
		model = defaultAIModel
	}

	content := js.Global().Get("Array").New()

	textPart := js.Global().Get("Object").New()
	textPart.Set("type", "text")
	textPart.Set("text", prompt)
	content.Call("push", textPart)

	imagePart := js.Global().Get("Object").New()
	imagePart.Set("type", "image_url")
	imageURLPayload := js.Global().Get("Object").New()
	imageURLPayload.Set("url", imageURL)
	imagePart.Set("image_url", imageURLPayload)
	content.Call("push", imagePart)

	messages := js.Global().Get("Array").New()
	user := js.Global().Get("Object").New()
	user.Set("role", "user")
	user.Set("content", content)
	messages.Call("push", user)

	input := js.Global().Get("Object").New()
	input.Set("messages", messages)

	return promise(func(resolve, reject js.Value) {
		var onResolve js.Func
		var onReject js.Func

		onResolve = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()

			payload := "null"
			if len(args) > 0 {
				payload = stringify(args[0])
			}
			resolve.Invoke(jsonResponse(payload))
			return nil
		})

		onReject = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()

			message := "Workers AI request failed"
			status := 502
			if len(args) > 0 {
				message = errorPayload(args[0])
				if code := errorStatus(args[0]); code > 0 {
					status = code
				}
			}
			resolve.Invoke(jsonTextResponse(status, message))
			return nil
		})

		ai.Call("run", model, input).Call("then", onResolve).Call("catch", onReject)
	})
}

func promise(fn func(resolve js.Value, reject js.Value)) js.Value {
	executor := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) >= 2 {
			fn(args[0], args[1])
		}
		return nil
	})
	defer executor.Release()

	return js.Global().Get("Promise").New(executor)
}

func stringify(value js.Value) string {
	output := js.Global().Get("JSON").Call("stringify", value)
	if output.IsUndefined() || output.IsNull() {
		return "null"
	}
	return output.String()
}

func errorPayload(value js.Value) string {
	payload := js.Global().Get("Object").New()
	payload.Set("name", value.Get("name"))
	payload.Set("message", value.Get("message"))
	payload.Set("code", firstDefined(value, "code", "status"))
	payload.Set("internalCode", firstDefined(value, "internalCode", "internal_code"))

	cause := value.Get("cause")
	if !cause.IsUndefined() && !cause.IsNull() {
		causePayload := js.Global().Get("Object").New()
		causePayload.Set("name", cause.Get("name"))
		causePayload.Set("message", cause.Get("message"))
		causePayload.Set("code", firstDefined(cause, "code", "status"))
		causePayload.Set("internalCode", firstDefined(cause, "internalCode", "internal_code"))
		payload.Set("cause", causePayload)
	}

	text := stringify(payload)
	if text == "{}" || text == "null" {
		return "{\"message\":\"Workers AI request failed\"}"
	}
	return text
}

func errorStatus(value js.Value) int {
	for _, key := range []string{"status", "statusCode", "code"} {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() && field.Type() == js.TypeNumber {
			return field.Int()
		}
	}
	return 0
}

func firstDefined(value js.Value, keys ...string) js.Value {
	for _, key := range keys {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() {
			return field
		}
	}
	return js.Null()
}

func searchParam(url js.Value, key string) string {
	value := url.Get("searchParams").Call("get", key)
	if value.IsUndefined() || value.IsNull() {
		return ""
	}
	return value.String()
}

func jsonResponse(body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "application/json")
	options := js.Global().Get("Object").New()
	options.Set("status", 200)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}

func jsonTextResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "application/json")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}

func textResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "text/plain; charset=utf-8")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}
`
}

func aiSTTWorkerMainTemplate() string {
	return `package main

import "syscall/js"

const defaultAIModel = "@cf/deepgram/nova-3"

func main() {
	js.Global().Set("handleRequest", js.FuncOf(handleRequest))
	js.Global().Set("handleScheduled", js.FuncOf(func(this js.Value, args []js.Value) any {
		return nil
	}))
	select {}
}

func handleRequest(this js.Value, args []js.Value) any {
	if len(args) < 2 {
		return textResponse(500, "missing request or env")
	}

	request := args[0]
	env := args[1]
	ai := env.Get("AI")
	if ai.IsUndefined() || ai.IsNull() {
		return textResponse(500, "Workers AI binding \"AI\" is not configured")
	}
	if request.Get("body").IsUndefined() || request.Get("body").IsNull() {
		return jsonTextResponse(400, "{\"message\":\"send audio bytes in the request body\"}")
	}

	url := js.Global().Get("URL").New(request.Get("url"))
	model := searchParam(url, "model")
	if model == "" {
		model = defaultAIModel
	}

	contentType := request.Get("headers").Call("get", "content-type")
	if contentType.IsUndefined() || contentType.IsNull() || contentType.String() == "" {
		contentType = js.ValueOf("audio/mpeg")
	}

	audio := js.Global().Get("Object").New()
	audio.Set("body", request.Get("body"))
	audio.Set("contentType", contentType)

	input := js.Global().Get("Object").New()
	input.Set("audio", audio)
	input.Set("detect_language", true)

	options := js.Global().Get("Object").New()
	options.Set("returnRawResponse", true)

	return promise(func(resolve, reject js.Value) {
		var onResolve js.Func
		var onReject js.Func

		onResolve = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()
			if len(args) > 0 {
				resolve.Invoke(args[0])
				return nil
			}
			resolve.Invoke(jsonTextResponse(502, "{\"message\":\"Workers AI returned no response\"}"))
			return nil
		})

		onReject = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()
			message := "Workers AI request failed"
			status := 502
			if len(args) > 0 {
				message = errorPayload(args[0])
				if code := errorStatus(args[0]); code > 0 {
					status = code
				}
			}
			resolve.Invoke(jsonTextResponse(status, message))
			return nil
		})

		ai.Call("run", model, input, options).Call("then", onResolve).Call("catch", onReject)
	})
}

func promise(fn func(resolve js.Value, reject js.Value)) js.Value {
	executor := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) >= 2 {
			fn(args[0], args[1])
		}
		return nil
	})
	defer executor.Release()

	return js.Global().Get("Promise").New(executor)
}

func stringify(value js.Value) string {
	output := js.Global().Get("JSON").Call("stringify", value)
	if output.IsUndefined() || output.IsNull() {
		return "null"
	}
	return output.String()
}

func errorPayload(value js.Value) string {
	payload := js.Global().Get("Object").New()
	payload.Set("name", value.Get("name"))
	payload.Set("message", value.Get("message"))
	payload.Set("code", firstDefined(value, "code", "status"))
	payload.Set("internalCode", firstDefined(value, "internalCode", "internal_code"))

	cause := value.Get("cause")
	if !cause.IsUndefined() && !cause.IsNull() {
		causePayload := js.Global().Get("Object").New()
		causePayload.Set("name", cause.Get("name"))
		causePayload.Set("message", cause.Get("message"))
		causePayload.Set("code", firstDefined(cause, "code", "status"))
		causePayload.Set("internalCode", firstDefined(cause, "internalCode", "internal_code"))
		payload.Set("cause", causePayload)
	}

	text := stringify(payload)
	if text == "{}" || text == "null" {
		return "{\"message\":\"Workers AI request failed\"}"
	}
	return text
}

func errorStatus(value js.Value) int {
	for _, key := range []string{"status", "statusCode", "code"} {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() && field.Type() == js.TypeNumber {
			return field.Int()
		}
	}
	return 0
}

func firstDefined(value js.Value, keys ...string) js.Value {
	for _, key := range keys {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() {
			return field
		}
	}
	return js.Null()
}

func searchParam(url js.Value, key string) string {
	value := url.Get("searchParams").Call("get", key)
	if value.IsUndefined() || value.IsNull() {
		return ""
	}
	return value.String()
}

func jsonTextResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "application/json")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}

func textResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "text/plain; charset=utf-8")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}
`
}

func aiTTSWorkerMainTemplate() string {
	return `package main

import "syscall/js"

const defaultAIModel = "@cf/deepgram/aura-2-en"

func main() {
	js.Global().Set("handleRequest", js.FuncOf(handleRequest))
	js.Global().Set("handleScheduled", js.FuncOf(func(this js.Value, args []js.Value) any {
		return nil
	}))
	select {}
}

func handleRequest(this js.Value, args []js.Value) any {
	if len(args) < 2 {
		return textResponse(500, "missing request or env")
	}

	request := args[0]
	env := args[1]
	ai := env.Get("AI")
	if ai.IsUndefined() || ai.IsNull() {
		return textResponse(500, "Workers AI binding \"AI\" is not configured")
	}

	url := js.Global().Get("URL").New(request.Get("url"))
	text := searchParam(url, "text")
	if text == "" {
		text = "Hello from a Go-based Cloudflare text to speech worker."
	}
	model := searchParam(url, "model")
	if model == "" {
		model = defaultAIModel
	}
	speaker := searchParam(url, "speaker")
	if speaker == "" {
		speaker = "luna"
	}

	input := js.Global().Get("Object").New()
	input.Set("text", text)
	input.Set("speaker", speaker)

	options := js.Global().Get("Object").New()
	options.Set("returnRawResponse", true)

	return promise(func(resolve, reject js.Value) {
		var onResolve js.Func
		var onReject js.Func

		onResolve = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()
			if len(args) > 0 {
				resolve.Invoke(args[0])
				return nil
			}
			resolve.Invoke(jsonTextResponse(502, "{\"message\":\"Workers AI returned no response\"}"))
			return nil
		})

		onReject = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()
			message := "Workers AI request failed"
			status := 502
			if len(args) > 0 {
				message = errorPayload(args[0])
				if code := errorStatus(args[0]); code > 0 {
					status = code
				}
			}
			resolve.Invoke(jsonTextResponse(status, message))
			return nil
		})

		ai.Call("run", model, input, options).Call("then", onResolve).Call("catch", onReject)
	})
}

func promise(fn func(resolve js.Value, reject js.Value)) js.Value {
	executor := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) >= 2 {
			fn(args[0], args[1])
		}
		return nil
	})
	defer executor.Release()

	return js.Global().Get("Promise").New(executor)
}

func stringify(value js.Value) string {
	output := js.Global().Get("JSON").Call("stringify", value)
	if output.IsUndefined() || output.IsNull() {
		return "null"
	}
	return output.String()
}

func errorPayload(value js.Value) string {
	payload := js.Global().Get("Object").New()
	payload.Set("name", value.Get("name"))
	payload.Set("message", value.Get("message"))
	payload.Set("code", firstDefined(value, "code", "status"))
	payload.Set("internalCode", firstDefined(value, "internalCode", "internal_code"))

	cause := value.Get("cause")
	if !cause.IsUndefined() && !cause.IsNull() {
		causePayload := js.Global().Get("Object").New()
		causePayload.Set("name", cause.Get("name"))
		causePayload.Set("message", cause.Get("message"))
		causePayload.Set("code", firstDefined(cause, "code", "status"))
		causePayload.Set("internalCode", firstDefined(cause, "internalCode", "internal_code"))
		payload.Set("cause", causePayload)
	}

	text := stringify(payload)
	if text == "{}" || text == "null" {
		return "{\"message\":\"Workers AI request failed\"}"
	}
	return text
}

func errorStatus(value js.Value) int {
	for _, key := range []string{"status", "statusCode", "code"} {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() && field.Type() == js.TypeNumber {
			return field.Int()
		}
	}
	return 0
}

func firstDefined(value js.Value, keys ...string) js.Value {
	for _, key := range keys {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() {
			return field
		}
	}
	return js.Null()
}

func searchParam(url js.Value, key string) string {
	value := url.Get("searchParams").Call("get", key)
	if value.IsUndefined() || value.IsNull() {
		return ""
	}
	return value.String()
}

func jsonTextResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "application/json")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}

func textResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "text/plain; charset=utf-8")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}
`
}

func aiImageWorkerMainTemplate() string {
	return `package main

import "syscall/js"

const defaultAIModel = "@cf/black-forest-labs/flux-2-klein-9b"

func main() {
	js.Global().Set("handleRequest", js.FuncOf(handleRequest))
	js.Global().Set("handleScheduled", js.FuncOf(func(this js.Value, args []js.Value) any {
		return nil
	}))
	select {}
}

func handleRequest(this js.Value, args []js.Value) any {
	if len(args) < 2 {
		return textResponse(500, "missing request or env")
	}

	request := args[0]
	env := args[1]
	ai := env.Get("AI")
	if ai.IsUndefined() || ai.IsNull() {
		return textResponse(500, "Workers AI binding \"AI\" is not configured")
	}

	url := js.Global().Get("URL").New(request.Get("url"))
	prompt := searchParam(url, "prompt")
	if prompt == "" {
		prompt = "A dramatic cloudscape over the Alps at sunset."
	}
	model := searchParam(url, "model")
	if model == "" {
		model = defaultAIModel
	}

	form := js.Global().Get("FormData").New()
	form.Call("append", "prompt", prompt)
	form.Call("append", "width", "1024")
	form.Call("append", "height", "1024")

	formResponse := js.Global().Get("Response").New(form)
	multipart := js.Global().Get("Object").New()
	multipart.Set("body", formResponse.Get("body"))
	multipart.Set("contentType", formResponse.Get("headers").Call("get", "content-type"))

	input := js.Global().Get("Object").New()
	input.Set("multipart", multipart)

	return promise(func(resolve, reject js.Value) {
		var onResolve js.Func
		var onReject js.Func

		onResolve = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()
			payload := "null"
			if len(args) > 0 {
				payload = stringify(args[0])
			}
			resolve.Invoke(jsonResponse(payload))
			return nil
		})

		onReject = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()
			message := "Workers AI request failed"
			status := 502
			if len(args) > 0 {
				message = errorPayload(args[0])
				if code := errorStatus(args[0]); code > 0 {
					status = code
				}
			}
			resolve.Invoke(jsonTextResponse(status, message))
			return nil
		})

		ai.Call("run", model, input).Call("then", onResolve).Call("catch", onReject)
	})
}

func promise(fn func(resolve js.Value, reject js.Value)) js.Value {
	executor := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) >= 2 {
			fn(args[0], args[1])
		}
		return nil
	})
	defer executor.Release()

	return js.Global().Get("Promise").New(executor)
}

func stringify(value js.Value) string {
	output := js.Global().Get("JSON").Call("stringify", value)
	if output.IsUndefined() || output.IsNull() {
		return "null"
	}
	return output.String()
}

func errorPayload(value js.Value) string {
	payload := js.Global().Get("Object").New()
	payload.Set("name", value.Get("name"))
	payload.Set("message", value.Get("message"))
	payload.Set("code", firstDefined(value, "code", "status"))
	payload.Set("internalCode", firstDefined(value, "internalCode", "internal_code"))

	cause := value.Get("cause")
	if !cause.IsUndefined() && !cause.IsNull() {
		causePayload := js.Global().Get("Object").New()
		causePayload.Set("name", cause.Get("name"))
		causePayload.Set("message", cause.Get("message"))
		causePayload.Set("code", firstDefined(cause, "code", "status"))
		causePayload.Set("internalCode", firstDefined(cause, "internalCode", "internal_code"))
		payload.Set("cause", causePayload)
	}

	text := stringify(payload)
	if text == "{}" || text == "null" {
		return "{\"message\":\"Workers AI request failed\"}"
	}
	return text
}

func errorStatus(value js.Value) int {
	for _, key := range []string{"status", "statusCode", "code"} {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() && field.Type() == js.TypeNumber {
			return field.Int()
		}
	}
	return 0
}

func firstDefined(value js.Value, keys ...string) js.Value {
	for _, key := range keys {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() {
			return field
		}
	}
	return js.Null()
}

func searchParam(url js.Value, key string) string {
	value := url.Get("searchParams").Call("get", key)
	if value.IsUndefined() || value.IsNull() {
		return ""
	}
	return value.String()
}

func jsonResponse(body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "application/json")
	options := js.Global().Get("Object").New()
	options.Set("status", 200)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}

func jsonTextResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "application/json")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}

func textResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "text/plain; charset=utf-8")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}
`
}

func aiEmbeddingsWorkerMainTemplate() string {
	return `package main

import "syscall/js"

const defaultAIModel = "@cf/qwen/qwen3-embedding-0.6b"

func main() {
	js.Global().Set("handleRequest", js.FuncOf(handleRequest))
	js.Global().Set("handleScheduled", js.FuncOf(func(this js.Value, args []js.Value) any {
		return nil
	}))
	select {}
}

func handleRequest(this js.Value, args []js.Value) any {
	if len(args) < 2 {
		return textResponse(500, "missing request or env")
	}

	request := args[0]
	env := args[1]
	ai := env.Get("AI")
	if ai.IsUndefined() || ai.IsNull() {
		return textResponse(500, "Workers AI binding \"AI\" is not configured")
	}

	url := js.Global().Get("URL").New(request.Get("url"))
	text := searchParam(url, "text")
	if text == "" {
		text = "Cloudflare Workers AI embeddings from Go."
	}
	model := searchParam(url, "model")
	if model == "" {
		model = defaultAIModel
	}

	input := js.Global().Get("Object").New()
	input.Set("text", text)

	return promise(func(resolve, reject js.Value) {
		var onResolve js.Func
		var onReject js.Func

		onResolve = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()
			payload := "null"
			if len(args) > 0 {
				payload = stringify(args[0])
			}
			resolve.Invoke(jsonResponse(payload))
			return nil
		})

		onReject = js.FuncOf(func(this js.Value, args []js.Value) any {
			defer onResolve.Release()
			defer onReject.Release()
			message := "Workers AI request failed"
			status := 502
			if len(args) > 0 {
				message = errorPayload(args[0])
				if code := errorStatus(args[0]); code > 0 {
					status = code
				}
			}
			resolve.Invoke(jsonTextResponse(status, message))
			return nil
		})

		ai.Call("run", model, input).Call("then", onResolve).Call("catch", onReject)
	})
}

func promise(fn func(resolve js.Value, reject js.Value)) js.Value {
	executor := js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) >= 2 {
			fn(args[0], args[1])
		}
		return nil
	})
	defer executor.Release()

	return js.Global().Get("Promise").New(executor)
}

func stringify(value js.Value) string {
	output := js.Global().Get("JSON").Call("stringify", value)
	if output.IsUndefined() || output.IsNull() {
		return "null"
	}
	return output.String()
}

func errorPayload(value js.Value) string {
	payload := js.Global().Get("Object").New()
	payload.Set("name", value.Get("name"))
	payload.Set("message", value.Get("message"))
	payload.Set("code", firstDefined(value, "code", "status"))
	payload.Set("internalCode", firstDefined(value, "internalCode", "internal_code"))

	cause := value.Get("cause")
	if !cause.IsUndefined() && !cause.IsNull() {
		causePayload := js.Global().Get("Object").New()
		causePayload.Set("name", cause.Get("name"))
		causePayload.Set("message", cause.Get("message"))
		causePayload.Set("code", firstDefined(cause, "code", "status"))
		causePayload.Set("internalCode", firstDefined(cause, "internalCode", "internal_code"))
		payload.Set("cause", causePayload)
	}

	text := stringify(payload)
	if text == "{}" || text == "null" {
		return "{\"message\":\"Workers AI request failed\"}"
	}
	return text
}

func errorStatus(value js.Value) int {
	for _, key := range []string{"status", "statusCode", "code"} {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() && field.Type() == js.TypeNumber {
			return field.Int()
		}
	}
	return 0
}

func firstDefined(value js.Value, keys ...string) js.Value {
	for _, key := range keys {
		field := value.Get(key)
		if !field.IsUndefined() && !field.IsNull() {
			return field
		}
	}
	return js.Null()
}

func searchParam(url js.Value, key string) string {
	value := url.Get("searchParams").Call("get", key)
	if value.IsUndefined() || value.IsNull() {
		return ""
	}
	return value.String()
}

func jsonResponse(body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "application/json")
	options := js.Global().Get("Object").New()
	options.Set("status", 200)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}

func jsonTextResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "application/json")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}

func textResponse(status int, body string) js.Value {
	headers := js.Global().Get("Headers").New()
	headers.Call("set", "content-type", "text/plain; charset=utf-8")
	options := js.Global().Get("Object").New()
	options.Set("status", status)
	options.Set("headers", headers)
	return js.Global().Get("Response").New(body, options)
}
`
}

func workerShimTemplate(wasmFile string) string {
	return fmt.Sprintf(`import "./wasm_exec.js";
import wasmModule from "./%s";

const go = new Go();
let ready;

function wasmInstance(result) {
  if (result instanceof WebAssembly.Instance) {
    return result;
  }
  if (result && result.instance instanceof WebAssembly.Instance) {
    return result.instance;
  }
  throw new TypeError("unsupported WebAssembly instantiate result");
}

async function boot() {
  if (!ready) {
    ready = (async () => {
      const result = await WebAssembly.instantiate(wasmModule, go.importObject);
      const runtime = go.run(wasmInstance(result));
      const waitForHandler = (async () => {
        for (let i = 0; i < 200; i += 1) {
          if (typeof globalThis.handleRequest === "function") {
            return;
          }
          await new Promise((resolve) => setTimeout(resolve, 5));
        }
        throw new Error("Go handler did not register globalThis.handleRequest");
      })();
      await Promise.race([
        waitForHandler,
        runtime.then(() => {
          throw new Error("Go runtime exited before handler registration");
        }),
      ]);
    })();
  }
  await ready;
}

function toResponse(result) {
  if (result instanceof Response) {
    return result;
  }
  if (typeof result === "string") {
    return new Response(result);
  }
  if (result && typeof result === "object" && "body" in result) {
    return new Response(result.body, {
      status: result.status ?? 200,
      headers: result.headers ?? {},
    });
  }
  return new Response("");
}

export default {
  async fetch(request, env, ctx) {
    await boot();
    return toResponse(await globalThis.handleRequest(request, env, ctx));
  },
  async scheduled(controller, env, ctx) {
    await boot();
    if (typeof globalThis.handleScheduled === "function") {
      await globalThis.handleScheduled(controller, env, ctx);
    }
  },
};
`, wasmFile)
}

func WorkerShimTemplate(wasmFile string) string {
	return workerShimTemplate(wasmFile)
}
